stages:
  - dependencies
  - style
  - build
  - test

dependencies:
  stage: dependencies
  tags:
    - sbt-jdk11
  script:
    - sbt dependencyUpdates

checkstyle_check:
  stage: style
  tags:
    - sbt-jdk11
  script:
    - sbt checkstyle

build:
  stage: build
  tags:
    - sbt-jdk11
  script:
    - sbt clean compile

test:
  stage: test
  tags:
    - sbt-jdk11
  script:
    - sbt test jacoco
