stages:
  - dependencies
  - style
  - build

dependencies:
  stage: dependencies
  tags:
    - sbt-jdk11
  script:
    - sbt dependencyUpdates

checkstyle_check:
  stage: style
  tags:
    - sbt-jdk11
  script:
    - sbt checkstyle

build:
  stage: build
  tags:
    - sbt-jdk11
  script:
    - sbt clean compile
